// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: im.proto

package im

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_COMMAND_NONE           Command = 0
	Command_SEND_MESSAGE           Command = 2
	Command_FETCH_MESSAGES         Command = 3
	Command_REPORT_ABUSE           Command = 4
	Command_SWITCH_LANGUAGE        Command = 5
	Command_USER_GROUP             Command = 6
	Command_SEND_TEXTING_MESSAGE   Command = 7
	Command_FETCH_TEXTING_MESSAGES Command = 8
	Command_SUBSCRIBE_CHAT         Command = 9
	Command_UNSUBSCRIBE_CHAT       Command = 10
	Command_PUSH_MESSAGE           Command = 100
	Command_PUSH_TEXTING_MESSAGE   Command = 101
	Command_READ_TEXTING_MESSAGE   Command = 102
	Command_FETCH_READ_POINTERS    Command = 103
	Command_USER_STATUS            Command = 200
	Command_GROUP_STATUS           Command = 201
	Command_GROUP_INFO             Command = 202
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0:   "COMMAND_NONE",
		2:   "SEND_MESSAGE",
		3:   "FETCH_MESSAGES",
		4:   "REPORT_ABUSE",
		5:   "SWITCH_LANGUAGE",
		6:   "USER_GROUP",
		7:   "SEND_TEXTING_MESSAGE",
		8:   "FETCH_TEXTING_MESSAGES",
		9:   "SUBSCRIBE_CHAT",
		10:  "UNSUBSCRIBE_CHAT",
		100: "PUSH_MESSAGE",
		101: "PUSH_TEXTING_MESSAGE",
		102: "READ_TEXTING_MESSAGE",
		103: "FETCH_READ_POINTERS",
		200: "USER_STATUS",
		201: "GROUP_STATUS",
		202: "GROUP_INFO",
	}
	Command_value = map[string]int32{
		"COMMAND_NONE":           0,
		"SEND_MESSAGE":           2,
		"FETCH_MESSAGES":         3,
		"REPORT_ABUSE":           4,
		"SWITCH_LANGUAGE":        5,
		"USER_GROUP":             6,
		"SEND_TEXTING_MESSAGE":   7,
		"FETCH_TEXTING_MESSAGES": 8,
		"SUBSCRIBE_CHAT":         9,
		"UNSUBSCRIBE_CHAT":       10,
		"PUSH_MESSAGE":           100,
		"PUSH_TEXTING_MESSAGE":   101,
		"READ_TEXTING_MESSAGE":   102,
		"FETCH_READ_POINTERS":    103,
		"USER_STATUS":            200,
		"GROUP_STATUS":           201,
		"GROUP_INFO":             202,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

type Language int32

const (
	Language_DEFAULT Language = 0
	Language_ZH_CN   Language = 1
	Language_EN_US   Language = 2
	Language_ZH_HK   Language = 3
	Language_ID_ID   Language = 4
	Language_MS_MY   Language = 5
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "DEFAULT",
		1: "ZH_CN",
		2: "EN_US",
		3: "ZH_HK",
		4: "ID_ID",
		5: "MS_MY",
	}
	Language_value = map[string]int32{
		"DEFAULT": 0,
		"ZH_CN":   1,
		"EN_US":   2,
		"ZH_HK":   3,
		"ID_ID":   4,
		"MS_MY":   5,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[1].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[1]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

type MessageEntity_ContentType int32

const (
	MessageEntity_CONTENT_TYPE_NONE MessageEntity_ContentType = 0
	MessageEntity_CHAT              MessageEntity_ContentType = 1
	MessageEntity_ORDER             MessageEntity_ContentType = 2
)

// Enum value maps for MessageEntity_ContentType.
var (
	MessageEntity_ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_NONE",
		1: "CHAT",
		2: "ORDER",
	}
	MessageEntity_ContentType_value = map[string]int32{
		"CONTENT_TYPE_NONE": 0,
		"CHAT":              1,
		"ORDER":             2,
	}
)

func (x MessageEntity_ContentType) Enum() *MessageEntity_ContentType {
	p := new(MessageEntity_ContentType)
	*p = x
	return p
}

func (x MessageEntity_ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageEntity_ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[2].Descriptor()
}

func (MessageEntity_ContentType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[2]
}

func (x MessageEntity_ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageEntity_ContentType.Descriptor instead.
func (MessageEntity_ContentType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4, 0}
}

type MessageEntity_Visible int32

const (
	MessageEntity_VISIBLE_NONE MessageEntity_Visible = 0
	MessageEntity_ALL          MessageEntity_Visible = 1
	MessageEntity_SENDER       MessageEntity_Visible = 2
)

// Enum value maps for MessageEntity_Visible.
var (
	MessageEntity_Visible_name = map[int32]string{
		0: "VISIBLE_NONE",
		1: "ALL",
		2: "SENDER",
	}
	MessageEntity_Visible_value = map[string]int32{
		"VISIBLE_NONE": 0,
		"ALL":          1,
		"SENDER":       2,
	}
)

func (x MessageEntity_Visible) Enum() *MessageEntity_Visible {
	p := new(MessageEntity_Visible)
	*p = x
	return p
}

func (x MessageEntity_Visible) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageEntity_Visible) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[3].Descriptor()
}

func (MessageEntity_Visible) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[3]
}

func (x MessageEntity_Visible) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageEntity_Visible.Descriptor instead.
func (MessageEntity_Visible) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4, 1}
}

type UserGroupStateArg_StateType int32

const (
	UserGroupStateArg_STATE_TYPE_NONE UserGroupStateArg_StateType = 0
	UserGroupStateArg_REGISTRATION    UserGroupStateArg_StateType = 1
	UserGroupStateArg_CANCELLATION    UserGroupStateArg_StateType = 2
)

// Enum value maps for UserGroupStateArg_StateType.
var (
	UserGroupStateArg_StateType_name = map[int32]string{
		0: "STATE_TYPE_NONE",
		1: "REGISTRATION",
		2: "CANCELLATION",
	}
	UserGroupStateArg_StateType_value = map[string]int32{
		"STATE_TYPE_NONE": 0,
		"REGISTRATION":    1,
		"CANCELLATION":    2,
	}
)

func (x UserGroupStateArg_StateType) Enum() *UserGroupStateArg_StateType {
	p := new(UserGroupStateArg_StateType)
	*p = x
	return p
}

func (x UserGroupStateArg_StateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserGroupStateArg_StateType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[4].Descriptor()
}

func (UserGroupStateArg_StateType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[4]
}

func (x UserGroupStateArg_StateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserGroupStateArg_StateType.Descriptor instead.
func (UserGroupStateArg_StateType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{12, 0}
}

type TextingMessage_ContentType int32

const (
	TextingMessage_CONTENT_TYPE_NONE TextingMessage_ContentType = 0
	TextingMessage_PLAIN_TEXT        TextingMessage_ContentType = 1
	TextingMessage_FILE              TextingMessage_ContentType = 2
)

// Enum value maps for TextingMessage_ContentType.
var (
	TextingMessage_ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_NONE",
		1: "PLAIN_TEXT",
		2: "FILE",
	}
	TextingMessage_ContentType_value = map[string]int32{
		"CONTENT_TYPE_NONE": 0,
		"PLAIN_TEXT":        1,
		"FILE":              2,
	}
)

func (x TextingMessage_ContentType) Enum() *TextingMessage_ContentType {
	p := new(TextingMessage_ContentType)
	*p = x
	return p
}

func (x TextingMessage_ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextingMessage_ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_proto_enumTypes[5].Descriptor()
}

func (TextingMessage_ContentType) Type() protoreflect.EnumType {
	return &file_im_proto_enumTypes[5]
}

func (x TextingMessage_ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextingMessage_ContentType.Descriptor instead.
func (TextingMessage_ContentType) EnumDescriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{13, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqID   string     `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Command Command    `protobuf:"varint,2,opt,name=command,proto3,enum=Command" json:"command,omitempty"`
	Data    *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetReqID() string {
	if x != nil {
		return x.ReqID
	}
	return ""
}

func (x *Request) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_NONE
}

func (x *Request) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type Push struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqID   string     `protobuf:"bytes,1,opt,name=reqID,proto3" json:"reqID,omitempty"`
	Command Command    `protobuf:"varint,2,opt,name=command,proto3,enum=Command" json:"command,omitempty"`
	Code    int32      `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string     `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Data    *anypb.Any `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Push) Reset() {
	*x = Push{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push) ProtoMessage() {}

func (x *Push) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push.ProtoReflect.Descriptor instead.
func (*Push) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

func (x *Push) GetReqID() string {
	if x != nil {
		return x.ReqID
	}
	return ""
}

func (x *Push) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_NONE
}

func (x *Push) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Push) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Push) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatIDsWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatIDs []int64 `protobuf:"varint,1,rep,packed,name=chatIDs,proto3" json:"chatIDs,omitempty"`
}

func (x *ChatIDsWrapper) Reset() {
	*x = ChatIDsWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatIDsWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIDsWrapper) ProtoMessage() {}

func (x *ChatIDsWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIDsWrapper.ProtoReflect.Descriptor instead.
func (*ChatIDsWrapper) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{2}
}

func (x *ChatIDsWrapper) GetChatIDs() []int64 {
	if x != nil {
		return x.ChatIDs
	}
	return nil
}

type MessageEntityWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageEntity []*MessageEntity `protobuf:"bytes,1,rep,name=messageEntity,proto3" json:"messageEntity,omitempty"`
}

func (x *MessageEntityWrapper) Reset() {
	*x = MessageEntityWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEntityWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEntityWrapper) ProtoMessage() {}

func (x *MessageEntityWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEntityWrapper.ProtoReflect.Descriptor instead.
func (*MessageEntityWrapper) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{3}
}

func (x *MessageEntityWrapper) GetMessageEntity() []*MessageEntity {
	if x != nil {
		return x.MessageEntity
	}
	return nil
}

type MessageEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID       int64                     `protobuf:"varint,1,opt,name=msgID,proto3" json:"msgID,omitempty"`
	ContentType MessageEntity_ContentType `protobuf:"varint,2,opt,name=contentType,proto3,enum=MessageEntity_ContentType" json:"contentType,omitempty"`
	VdID        int64                     `protobuf:"varint,3,opt,name=vdID,proto3" json:"vdID,omitempty"`
	Sender      int64                     `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName  string                    `protobuf:"bytes,5,opt,name=senderName,proto3" json:"senderName,omitempty"`
	ChatID      int64                     `protobuf:"varint,6,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Vip         int32                     `protobuf:"varint,7,opt,name=vip,proto3" json:"vip,omitempty"`
	Avatar      int32                     `protobuf:"varint,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ReplyTo     int64                     `protobuf:"varint,9,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
	Content     string                    `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Visible     MessageEntity_Visible     `protobuf:"varint,11,opt,name=visible,proto3,enum=MessageEntity_Visible" json:"visible,omitempty"`
	Timestamp   int64                     `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MessageEntity) Reset() {
	*x = MessageEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEntity) ProtoMessage() {}

func (x *MessageEntity) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEntity.ProtoReflect.Descriptor instead.
func (*MessageEntity) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4}
}

func (x *MessageEntity) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *MessageEntity) GetContentType() MessageEntity_ContentType {
	if x != nil {
		return x.ContentType
	}
	return MessageEntity_CONTENT_TYPE_NONE
}

func (x *MessageEntity) GetVdID() int64 {
	if x != nil {
		return x.VdID
	}
	return 0
}

func (x *MessageEntity) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *MessageEntity) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *MessageEntity) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

func (x *MessageEntity) GetVip() int32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

func (x *MessageEntity) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *MessageEntity) GetReplyTo() int64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *MessageEntity) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEntity) GetVisible() MessageEntity_Visible {
	if x != nil {
		return x.Visible
	}
	return MessageEntity_VISIBLE_NONE
}

func (x *MessageEntity) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FetchArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pointer int64 `protobuf:"varint,1,opt,name=pointer,proto3" json:"pointer,omitempty"`
	ChatID  int64 `protobuf:"varint,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
}

func (x *FetchArgs) Reset() {
	*x = FetchArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchArgs) ProtoMessage() {}

func (x *FetchArgs) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchArgs.ProtoReflect.Descriptor instead.
func (*FetchArgs) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{5}
}

func (x *FetchArgs) GetPointer() int64 {
	if x != nil {
		return x.Pointer
	}
	return 0
}

func (x *FetchArgs) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

type ReportAbuseArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ReportAbuseArgs) Reset() {
	*x = ReportAbuseArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportAbuseArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAbuseArgs) ProtoMessage() {}

func (x *ReportAbuseArgs) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAbuseArgs.ProtoReflect.Descriptor instead.
func (*ReportAbuseArgs) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{6}
}

func (x *ReportAbuseArgs) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReportAbuseArgs) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command Command    `protobuf:"varint,1,opt,name=command,proto3,enum=Command" json:"command,omitempty"`
	Data    *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Notify) Reset() {
	*x = Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{7}
}

func (x *Notify) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_NONE
}

func (x *Notify) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VdID   int64  `protobuf:"varint,2,opt,name=vdID,proto3" json:"vdID,omitempty"`
	Status int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UserStatus) Reset() {
	*x = UserStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatus) ProtoMessage() {}

func (x *UserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatus.ProtoReflect.Descriptor instead.
func (*UserStatus) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{8}
}

func (x *UserStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserStatus) GetVdID() int64 {
	if x != nil {
		return x.VdID
	}
	return 0
}

func (x *UserStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SwitchLanguageArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *SwitchLanguageArg) Reset() {
	*x = SwitchLanguageArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchLanguageArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchLanguageArg) ProtoMessage() {}

func (x *SwitchLanguageArg) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchLanguageArg.ProtoReflect.Descriptor instead.
func (*SwitchLanguageArg) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{9}
}

func (x *SwitchLanguageArg) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl     string `protobuf:"bytes,3,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	MemberCount int32  `protobuf:"varint,4,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	Deleted     int32  `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{10}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Group) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Group) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type GroupsWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *GroupsWrapper) Reset() {
	*x = GroupsWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupsWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsWrapper) ProtoMessage() {}

func (x *GroupsWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsWrapper.ProtoReflect.Descriptor instead.
func (*GroupsWrapper) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{11}
}

func (x *GroupsWrapper) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type UserGroupStateArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  int64                       `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	GroupID int64                       `protobuf:"varint,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Status  UserGroupStateArg_StateType `protobuf:"varint,4,opt,name=Status,proto3,enum=UserGroupStateArg_StateType" json:"Status,omitempty"`
}

func (x *UserGroupStateArg) Reset() {
	*x = UserGroupStateArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroupStateArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupStateArg) ProtoMessage() {}

func (x *UserGroupStateArg) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupStateArg.ProtoReflect.Descriptor instead.
func (*UserGroupStateArg) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{12}
}

func (x *UserGroupStateArg) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserGroupStateArg) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *UserGroupStateArg) GetStatus() UserGroupStateArg_StateType {
	if x != nil {
		return x.Status
	}
	return UserGroupStateArg_STATE_TYPE_NONE
}

type TextingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID       int64                      `protobuf:"varint,1,opt,name=msgID,proto3" json:"msgID,omitempty"`
	ContentType TextingMessage_ContentType `protobuf:"varint,2,opt,name=contentType,proto3,enum=TextingMessage_ContentType" json:"contentType,omitempty"`
	VdID        int64                      `protobuf:"varint,3,opt,name=vdID,proto3" json:"vdID,omitempty"`
	Sender      int64                      `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName  string                     `protobuf:"bytes,5,opt,name=senderName,proto3" json:"senderName,omitempty"`
	GroupID     int64                      `protobuf:"varint,6,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Avatar      int32                      `protobuf:"varint,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ReplyTo     int64                      `protobuf:"varint,8,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
	Content     string                     `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp   int64                      `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TextingMessage) Reset() {
	*x = TextingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextingMessage) ProtoMessage() {}

func (x *TextingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextingMessage.ProtoReflect.Descriptor instead.
func (*TextingMessage) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{13}
}

func (x *TextingMessage) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *TextingMessage) GetContentType() TextingMessage_ContentType {
	if x != nil {
		return x.ContentType
	}
	return TextingMessage_CONTENT_TYPE_NONE
}

func (x *TextingMessage) GetVdID() int64 {
	if x != nil {
		return x.VdID
	}
	return 0
}

func (x *TextingMessage) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *TextingMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *TextingMessage) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *TextingMessage) GetAvatar() int32 {
	if x != nil {
		return x.Avatar
	}
	return 0
}

func (x *TextingMessage) GetReplyTo() int64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *TextingMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextingMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TextingMessageWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*TextingMessage `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *TextingMessageWrapper) Reset() {
	*x = TextingMessageWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextingMessageWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextingMessageWrapper) ProtoMessage() {}

func (x *TextingMessageWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextingMessageWrapper.ProtoReflect.Descriptor instead.
func (*TextingMessageWrapper) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{14}
}

func (x *TextingMessageWrapper) GetMsgs() []*TextingMessage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type FetchTextingMessageArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pointer int64 `protobuf:"varint,1,opt,name=pointer,proto3" json:"pointer,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
}

func (x *FetchTextingMessageArg) Reset() {
	*x = FetchTextingMessageArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchTextingMessageArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTextingMessageArg) ProtoMessage() {}

func (x *FetchTextingMessageArg) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTextingMessageArg.ProtoReflect.Descriptor instead.
func (*FetchTextingMessageArg) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{15}
}

func (x *FetchTextingMessageArg) GetPointer() int64 {
	if x != nil {
		return x.Pointer
	}
	return 0
}

func (x *FetchTextingMessageArg) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

type ReadTextingMessageArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pointer int64 `protobuf:"varint,1,opt,name=pointer,proto3" json:"pointer,omitempty"`
	GroupID int64 `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	UserID  int64 `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *ReadTextingMessageArg) Reset() {
	*x = ReadTextingMessageArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTextingMessageArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTextingMessageArg) ProtoMessage() {}

func (x *ReadTextingMessageArg) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTextingMessageArg.ProtoReflect.Descriptor instead.
func (*ReadTextingMessageArg) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{16}
}

func (x *ReadTextingMessageArg) GetPointer() int64 {
	if x != nil {
		return x.Pointer
	}
	return 0
}

func (x *ReadTextingMessageArg) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *ReadTextingMessageArg) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ReadPointer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID int64 `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Pointer int64 `protobuf:"varint,2,opt,name=pointer,proto3" json:"pointer,omitempty"`
}

func (x *ReadPointer) Reset() {
	*x = ReadPointer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPointer) ProtoMessage() {}

func (x *ReadPointer) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPointer.ProtoReflect.Descriptor instead.
func (*ReadPointer) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{17}
}

func (x *ReadPointer) GetGroupID() int64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *ReadPointer) GetPointer() int64 {
	if x != nil {
		return x.Pointer
	}
	return 0
}

type ReadPointerWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pointers []*ReadPointer `protobuf:"bytes,1,rep,name=pointers,proto3" json:"pointers,omitempty"`
}

func (x *ReadPointerWrapper) Reset() {
	*x = ReadPointerWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadPointerWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPointerWrapper) ProtoMessage() {}

func (x *ReadPointerWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPointerWrapper.ProtoReflect.Descriptor instead.
func (*ReadPointerWrapper) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{18}
}

func (x *ReadPointerWrapper) GetPointers() []*ReadPointer {
	if x != nil {
		return x.Pointers
	}
	return nil
}

var File_im_proto protoreflect.FileDescriptor

var file_im_proto_rawDesc = []byte{
	0x0a, 0x08, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x90, 0x01, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x71, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x28, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x49,
	0x44, 0x73, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x74, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x44, 0x73, 0x22, 0x4c, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0d, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0xe2, 0x03, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x3c, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x64, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x76, 0x64, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x69, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x69, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x76, 0x69, 0x73,
	0x69, 0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x54,
	0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x43, 0x48, 0x41, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x10, 0x02, 0x22, 0x30, 0x0a, 0x07, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x0c, 0x56, 0x49, 0x53, 0x49, 0x42, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45,
	0x4e, 0x44, 0x45, 0x52, 0x10, 0x02, 0x22, 0x3d, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x44, 0x22, 0x41, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41,
	0x62, 0x75, 0x73, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x4c, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x76, 0x64, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f,
	0x0a, 0x11, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x41, 0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22,
	0x81, 0x01, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x22, 0x2f, 0x0a, 0x0d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x22, 0xc1, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x41, 0x72, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x41, 0x72, 0x67,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x44, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x13, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c,
	0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x22, 0xf5, 0x02, 0x0a, 0x0e, 0x54, 0x65, 0x78,
	0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x44, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x69, 0x6e, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x76, 0x64, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x76, 0x64, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x3e, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x41, 0x49, 0x4e, 0x5f,
	0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02,
	0x22, 0x3c, 0x0a, 0x15, 0x54, 0x65, 0x78, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x73, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x69, 0x6e,
	0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x4c,
	0x0a, 0x16, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x63, 0x0a, 0x15,
	0x52, 0x65, 0x61, 0x64, 0x54, 0x65, 0x78, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x41, 0x72, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x41, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x08, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x2a, 0xed, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x53, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x50, 0x4f,
	0x52, 0x54, 0x5f, 0x41, 0x42, 0x55, 0x53, 0x45, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x57,
	0x49, 0x54, 0x43, 0x48, 0x5f, 0x4c, 0x41, 0x4e, 0x47, 0x55, 0x41, 0x47, 0x45, 0x10, 0x05, 0x12,
	0x0e, 0x0a, 0x0a, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x06, 0x12,
	0x18, 0x0a, 0x14, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x49, 0x4e, 0x47, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x07, 0x12, 0x1a, 0x0a, 0x16, 0x46, 0x45, 0x54,
	0x43, 0x48, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41,
	0x47, 0x45, 0x53, 0x10, 0x08, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49,
	0x42, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x09, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x53,
	0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x0a, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10,
	0x64, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x49, 0x4e,
	0x47, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x10, 0x66, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x45, 0x54, 0x43, 0x48, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x53, 0x10, 0x67, 0x12, 0x10,
	0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0xc8, 0x01,
	0x12, 0x11, 0x0a, 0x0c, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x10, 0xc9, 0x01, 0x12, 0x0f, 0x0a, 0x0a, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x10, 0xca, 0x01, 0x2a, 0x4e, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x5a, 0x48, 0x5f, 0x43, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4e, 0x5f, 0x55,
	0x53, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x5a, 0x48, 0x5f, 0x48, 0x4b, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x53, 0x5f,
	0x4d, 0x59, 0x10, 0x05, 0x42, 0x0d, 0x5a, 0x0b, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_im_proto_rawDescOnce sync.Once
	file_im_proto_rawDescData = file_im_proto_rawDesc
)

func file_im_proto_rawDescGZIP() []byte {
	file_im_proto_rawDescOnce.Do(func() {
		file_im_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_proto_rawDescData)
	})
	return file_im_proto_rawDescData
}

var file_im_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_im_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_im_proto_goTypes = []interface{}{
	(Command)(0),                     // 0: Command
	(Language)(0),                    // 1: Language
	(MessageEntity_ContentType)(0),   // 2: MessageEntity.ContentType
	(MessageEntity_Visible)(0),       // 3: MessageEntity.Visible
	(UserGroupStateArg_StateType)(0), // 4: UserGroupStateArg.StateType
	(TextingMessage_ContentType)(0),  // 5: TextingMessage.ContentType
	(*Request)(nil),                  // 6: Request
	(*Push)(nil),                     // 7: Push
	(*ChatIDsWrapper)(nil),           // 8: ChatIDsWrapper
	(*MessageEntityWrapper)(nil),     // 9: MessageEntityWrapper
	(*MessageEntity)(nil),            // 10: MessageEntity
	(*FetchArgs)(nil),                // 11: FetchArgs
	(*ReportAbuseArgs)(nil),          // 12: ReportAbuseArgs
	(*Notify)(nil),                   // 13: Notify
	(*UserStatus)(nil),               // 14: UserStatus
	(*SwitchLanguageArg)(nil),        // 15: SwitchLanguageArg
	(*Group)(nil),                    // 16: Group
	(*GroupsWrapper)(nil),            // 17: GroupsWrapper
	(*UserGroupStateArg)(nil),        // 18: UserGroupStateArg
	(*TextingMessage)(nil),           // 19: TextingMessage
	(*TextingMessageWrapper)(nil),    // 20: TextingMessageWrapper
	(*FetchTextingMessageArg)(nil),   // 21: FetchTextingMessageArg
	(*ReadTextingMessageArg)(nil),    // 22: ReadTextingMessageArg
	(*ReadPointer)(nil),              // 23: ReadPointer
	(*ReadPointerWrapper)(nil),       // 24: ReadPointerWrapper
	(*anypb.Any)(nil),                // 25: google.protobuf.Any
}
var file_im_proto_depIdxs = []int32{
	0,  // 0: Request.command:type_name -> Command
	25, // 1: Request.data:type_name -> google.protobuf.Any
	0,  // 2: Push.command:type_name -> Command
	25, // 3: Push.data:type_name -> google.protobuf.Any
	10, // 4: MessageEntityWrapper.messageEntity:type_name -> MessageEntity
	2,  // 5: MessageEntity.contentType:type_name -> MessageEntity.ContentType
	3,  // 6: MessageEntity.visible:type_name -> MessageEntity.Visible
	0,  // 7: Notify.command:type_name -> Command
	25, // 8: Notify.data:type_name -> google.protobuf.Any
	16, // 9: GroupsWrapper.groups:type_name -> Group
	4,  // 10: UserGroupStateArg.Status:type_name -> UserGroupStateArg.StateType
	5,  // 11: TextingMessage.contentType:type_name -> TextingMessage.ContentType
	19, // 12: TextingMessageWrapper.msgs:type_name -> TextingMessage
	23, // 13: ReadPointerWrapper.pointers:type_name -> ReadPointer
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_im_proto_init() }
func file_im_proto_init() {
	if File_im_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Push); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatIDsWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEntityWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportAbuseArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchLanguageArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupsWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroupStateArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextingMessageWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchTextingMessageArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTextingMessageArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPointer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadPointerWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_im_proto_goTypes,
		DependencyIndexes: file_im_proto_depIdxs,
		EnumInfos:         file_im_proto_enumTypes,
		MessageInfos:      file_im_proto_msgTypes,
	}.Build()
	File_im_proto = out.File
	file_im_proto_rawDesc = nil
	file_im_proto_goTypes = nil
	file_im_proto_depIdxs = nil
}
